services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: marked_here_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
